/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Lightr {
  export type InvitationStruct = {
    from: AddressLike;
    to: AddressLike;
    status: BigNumberish;
  };

  export type InvitationStructOutput = [
    from: string,
    to: string,
    status: bigint
  ] & { from: string; to: string; status: bigint };

  export type MessageStruct = {
    id: BigNumberish;
    content: string;
    from: AddressLike;
    to: AddressLike;
    date: BigNumberish;
  };

  export type MessageStructOutput = [
    id: bigint,
    content: string,
    from: string,
    to: string,
    date: bigint
  ] & { id: bigint; content: string; from: string; to: string; date: bigint };

  export type UserStruct = {
    id: BigNumberish;
    userName: string;
    userId: AddressLike;
    email: BytesLike;
    number: BytesLike;
    pass: BytesLike;
    profile: string;
  };

  export type UserStructOutput = [
    id: bigint,
    userName: string,
    userId: string,
    email: string,
    number: string,
    pass: string,
    profile: string
  ] & {
    id: bigint;
    userName: string;
    userId: string;
    email: string;
    number: string;
    pass: string;
    profile: string;
  };
}

export interface LightrInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptInvitation"
      | "getFriendsList"
      | "getInvitations"
      | "getUserMessages"
      | "getUserProfile"
      | "ignoreInvitation"
      | "inviteFriend"
      | "logIn"
      | "register"
      | "sendMessage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Accept"
      | "Invite"
      | "Login"
      | "Registered"
      | "SendMessage"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptInvitation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFriendsList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInvitations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMessages",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ignoreInvitation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inviteFriend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logIn",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptInvitation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFriendsList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvitations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ignoreInvitation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inviteFriend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
}

export namespace AcceptEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InviteEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoginEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisteredEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SendMessageEvent {
  export type InputTuple = [from: AddressLike, content: string];
  export type OutputTuple = [from: string, content: string];
  export interface OutputObject {
    from: string;
    content: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Lightr extends BaseContract {
  connect(runner?: ContractRunner | null): Lightr;
  waitForDeployment(): Promise<this>;

  interface: LightrInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptInvitation: TypedContractMethod<
    [invitationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFriendsList: TypedContractMethod<[], [string[]], "view">;

  getInvitations: TypedContractMethod<
    [],
    [Lightr.InvitationStructOutput[]],
    "view"
  >;

  getUserMessages: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [Lightr.MessageStructOutput[]],
    "view"
  >;

  getUserProfile: TypedContractMethod<
    [userId: AddressLike],
    [Lightr.UserStructOutput],
    "view"
  >;

  ignoreInvitation: TypedContractMethod<
    [invitationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  inviteFriend: TypedContractMethod<
    [friendAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  logIn: TypedContractMethod<
    [email: string, number: string, pass: string],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<
    [
      userName: string,
      number: string,
      email: string,
      pass: string,
      profile: string
    ],
    [void],
    "nonpayable"
  >;

  sendMessage: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _content: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptInvitation"
  ): TypedContractMethod<[invitationIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getFriendsList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getInvitations"
  ): TypedContractMethod<[], [Lightr.InvitationStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getUserMessages"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike],
    [Lightr.MessageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserProfile"
  ): TypedContractMethod<
    [userId: AddressLike],
    [Lightr.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "ignoreInvitation"
  ): TypedContractMethod<[invitationIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "inviteFriend"
  ): TypedContractMethod<[friendAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "logIn"
  ): TypedContractMethod<
    [email: string, number: string, pass: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      userName: string,
      number: string,
      email: string,
      pass: string,
      profile: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _content: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Accept"
  ): TypedContractEvent<
    AcceptEvent.InputTuple,
    AcceptEvent.OutputTuple,
    AcceptEvent.OutputObject
  >;
  getEvent(
    key: "Invite"
  ): TypedContractEvent<
    InviteEvent.InputTuple,
    InviteEvent.OutputTuple,
    InviteEvent.OutputObject
  >;
  getEvent(
    key: "Login"
  ): TypedContractEvent<
    LoginEvent.InputTuple,
    LoginEvent.OutputTuple,
    LoginEvent.OutputObject
  >;
  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;
  getEvent(
    key: "SendMessage"
  ): TypedContractEvent<
    SendMessageEvent.InputTuple,
    SendMessageEvent.OutputTuple,
    SendMessageEvent.OutputObject
  >;

  filters: {
    "Accept(address,address)": TypedContractEvent<
      AcceptEvent.InputTuple,
      AcceptEvent.OutputTuple,
      AcceptEvent.OutputObject
    >;
    Accept: TypedContractEvent<
      AcceptEvent.InputTuple,
      AcceptEvent.OutputTuple,
      AcceptEvent.OutputObject
    >;

    "Invite(address,address)": TypedContractEvent<
      InviteEvent.InputTuple,
      InviteEvent.OutputTuple,
      InviteEvent.OutputObject
    >;
    Invite: TypedContractEvent<
      InviteEvent.InputTuple,
      InviteEvent.OutputTuple,
      InviteEvent.OutputObject
    >;

    "Login(address)": TypedContractEvent<
      LoginEvent.InputTuple,
      LoginEvent.OutputTuple,
      LoginEvent.OutputObject
    >;
    Login: TypedContractEvent<
      LoginEvent.InputTuple,
      LoginEvent.OutputTuple,
      LoginEvent.OutputObject
    >;

    "Registered(address)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;

    "SendMessage(address,string)": TypedContractEvent<
      SendMessageEvent.InputTuple,
      SendMessageEvent.OutputTuple,
      SendMessageEvent.OutputObject
    >;
    SendMessage: TypedContractEvent<
      SendMessageEvent.InputTuple,
      SendMessageEvent.OutputTuple,
      SendMessageEvent.OutputObject
    >;
  };
}
